services:
  opsmind-frontend:
    container_name: opsmind-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:85"
    environment:
      # If your backend runs on the same Docker network, you can point the UI to it
      # Example: http://tickets-service:8080/api
      OPSMIND_API_URL: http://localhost:3001
      NODE_ENV: production
      PORT: 80
    networks:
      - opsmind-net

networks:
  opsmind-net:
    name: opsmind-net
    driver: bridge
    external: true
